{% set name = "pyincore" %}
{% set version = "1.4.1" %}
 
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: /path/to/pyincore

about:
  home: https://incore.ncsa.illinois.edu
  license: MPL-2.0
  summary: 'Python library for IN-CORE (Interdependent Networked Community Resilience Modeling Environment)'
  description: 'pyIncore is a component of IN-CORE. It is a python package consisting of two primary components: 
  1) a set of service classes to interact with the IN-CORE web services, and 2) IN-CORE analyses. The pyIncore 
  package allows users to apply various hazards to infrastructure in selected areas, propagating the effect of 
  physical infrastructure damage and loss of functionality to social and economic impacts.'
  dev_url: https://github.com/IN-CORE/pyincore
  doc_url: https://incore.ncsa.illinois.edu/doc/incore

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  #number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv . " # verbose
 
requirements:
  build:
    - python>=3.8
    - pip
    - numpy>=1.16
 
  host:
    - python>=3.6
    - pip
    - numpy>=1.16

  run:
    - python>=3.6
    - ipopt>=3.11
    - {{ pin_compatible('numpy') }}
    - fiona==1.8.21
    - geopandas==0.11.0
    - matplotlib==3.5.2
    - networkx==2.8.4
    - pandas==1.4.3
    - pyomo==6.4.1
    - pyproj==3.3.1
    - rasterio==1.2.10
    - requests==2.28.0
    - rtree==1.0.0
    - scipy==1.8.1
    - shapely==1.8.2
    - wntr==v0.4.2

test:
  # Python imports
  imports:
    - pyincore
    - pyomo
   
  requires:
    # Put any additional test requirements here.  For example
    - pytest>=3.9
    - pycodestyle==2.8.0
    - python-jose==3.3.0

  commands:
    # You can put built-in test commands to be run here.  Use this to test that the entry points work.
    python -c "import pyincore; print('SUCCESS')" #; pyincore.test_client()"
    # You can also put a file called run_test.py in the recipe that will be run at test time.
