name: pytests

# Runs unit tests on:
#  - any push to any branch
#  - when a PR is opened/reopened - this is just for additional safety and covers the case of main -> develop PRs without new pushes

# TODO: Use mamba instead of conda for installing packages. Improves on ~5mins it takes to install requirements.
#  https://github.com/mamba-org/provision-with-micromamba

on:
  push:

  pull_request:
     types: [opened, reopened]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ] # 3.10 and 3.11 have conflicts with environment.yml
    name: Python ${{ matrix.python-version }} Test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install miniconda with mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-file: environment.yml
          init-shell: >-
            bash
            powershell
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          post-cleanup: 'none'

      - name: Run tests with pytest
        run: |
          echo "${{secrets.PYTEST_USER_TOKEN}}" > tests/pyincore/.incorepw
          $CONDA/bin/python -m pytest --ignore=tests/test_format.py --ignore=tests/pyincore/analyses
