name: Python version tests

# Runs unit tests on:
#  - any push to any branch
#  - when a PR is opened/reopened - this is just for additional safety and covers the case of main -> develop PRs without new pushes

# TODO: Use mamba instead of conda for installing packages. Improves on ~5mins it takes to install requirements.
#  https://github.com/mamba-org/provision-with-micromamba

on:
  push:

  pull_request:
     types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
        run: |
            echo "${{secrets.PYTEST_USER_TOKEN}}" > tests/pyincore/.incorepw
            $CONDA/bin/python -m pytest --ignore=tests/test_format.py --ignore=tests/pyincore/analyses